// This file is automatically generated. Do not edit it directly.
import { createBrowserClient } from '@supabase/auth-helpers-react';

const SUPABASE_URL = "https://quuecudndfztjlxbrvyb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF1dWVjdWRuZGZ6dGpseGJydnliIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2MTQ3MzcsImV4cCI6MjA3MDE5MDczN30.-0jt-qpUh9beb0Mt-G1jHIsJ-XBFirqZ4gqVWXzCSMc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createBrowserClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);